In [1]:
import math # 수학 라이브러리

In [2]:
math.cos(90)

-0.4480736161291701

In [3]:
math.pow(2, 10) # 2의 10승

1024.0

### numpy 
- n 차원 배열 (ndarray)
- Python의 list, tuple 등 : 여러 항목으로 구성된 data를 다루는데 사용할 수 있다.
- Numpy module
   * Numerical Python
   * 다루어야 할 data가 모두 숫자인 경우, 계산 속도를 개선하기 위해 사용
   * 수학에서의 벡터(1차원 배열), 메트릭스(2차원, 3차원 등) 등 다차원 배열(array)을 계산하는데 유리
   * data 분석에서는 주로 숫자 배열을 다루는 경우가 많아 Numpy 라이브러리가 제공하는 ndarray를 사용하면 편리, 속도도 빠르다.
   * 배열에서 각 항목은 모두 동일한 type의 숫자(정수, 부동소수 등)이어야 한다.

In [4]:
import numpy # numpy 라이브러리를 바로 호출, numpy라는 이름을 사용

In [5]:
import numpy as np # np라는 약어 사용, numpy 라이브러리를 바로 호출

In [6]:
a=np.array([1, 5, 9])
print(a)
type(a)

[1 5 9]


numpy.ndarray

In [2]:
from numpy import * # numpy 라이브러리를 바로 호출, 이름사용x

In [4]:
b=array([2, 5, 12])
print(b)
type(b)

[ 2  5 12]


numpy.ndarray

In [3]:
listA=[1, 2, 10]
print(listA)
print(listA * 3)
# 리스트에 숫자를 곱하면, 동일한 리스트가 숫자만큼 복사
# print(listA + 100) -> 에러: list는 계산 못함

[1, 2, 10]
[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [6]:
arr=np.array(listA)
print(arr)
print(arr * 3)
print(arr + 100)
# 배열에 숫자를 곱,더하면 모든 항목에 적용됨 -> 벡터화

print(arr.shape)    # *행 *열을 출력
print(arr.size)     # 원소의 크기
print(arr.ndim)     # 차원
print(arr.dtype)    # 원소의 데이터 형식
print(arr.itemsize) # 원소의 데이터 형식의 크기
print(type(arr))   # 변수의 데이터형

[ 1  2 10]
[ 3  6 30]
[101 102 110]
(3,)
3
1
int32
4
<class 'numpy.ndarray'>


In [12]:
data=[[1.0, 2.5, 3.2], [4, 5, 6], [7, 8, 9], [5, 6, 4]]
data2=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(data + data2)
print(data)
print(data * 3)

[[1.0, 2.5, 3.2], [4, 5, 6], [7, 8, 9], [5, 6, 4], [1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1.0, 2.5, 3.2], [4, 5, 6], [7, 8, 9], [5, 6, 4]]
[[1.0, 2.5, 3.2], [4, 5, 6], [7, 8, 9], [5, 6, 4], [1.0, 2.5, 3.2], [4, 5, 6], [7, 8, 9], [5, 6, 4], [1.0, 2.5, 3.2], [4, 5, 6], [7, 8, 9], [5, 6, 4]]


In [17]:
data3 = np.array(data)
data4 = np.array(data2)
print(data3)
print(data4)

[[1.  2.5 3.2]
 [4.  5.  6. ]
 [7.  8.  9. ]
 [5.  6.  4. ]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
data6 = np.array(data)
data5 = data3 + data6 # 배열끼리 계산은 행과 열의 크기가 동일해야 함
print(data5)
print(data5 + 100)

[[ 2.   5.   6.4]
 [ 8.  10.  12. ]
 [14.  16.  18. ]
 [10.  12.   8. ]]
[[102.  105.  106.4]
 [108.  110.  112. ]
 [114.  116.  118. ]
 [110.  112.  108. ]]


In [21]:
print(data5.shape)
print(data5.size)
print(data5.ndim)
print(data5.dtype)
print(data5.itemsize)
print(type(data5))

(4, 3)
12
2
int32
4
<class 'numpy.ndarray'>


In [21]:
data5[1,1], data5[1][1] # 1행 1열, tuple 형태

(10.0, 10.0)

### Slice
- 행(row) 또는 열(column)의 일부를 얻으려고 할 때 사용
- [start:last] 
    * default start=0, last=n
    * slicing 범위 : start ~ (last-1) 
- [ : ] : 전체
- [0:n] : 0번째 ~ (n-1)번째
- [ :5] : 0번째 ~ 4번째
- [2: ] : 2번째 ~ 마지막(끝까지)
- [-1] : 제일 마지막 항목
- [-2] : 제일 마지막에서 두번째 항목

In [23]:
data5[0,2:] # 0행, 2~끝열

array([6.4])

In [27]:
data5[:2, 1:] # 0~1행, 1~끝열

array([[ 4,  6],
       [10, 12]])

In [36]:
data5[:3] # 0~2행, 전체 열

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [26]:
data5[:, 2] # 전체 행, 2열

array([ 6.4, 12. , 18. ,  8. ])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# range 범위 만들기
x = range(5)
print(type(x))
x

<class 'range'>


range(0, 5)

In [27]:
y = np.arange(5)
print(type(y)) ; y

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [29]:
# 데이터 타입 변경: astype
z = y.astype(np.float32) ; z

array([0., 1., 2., 3., 4.], dtype=float32)

In [45]:
data = np.arange(12) ; data # 0~11, 1차원 배열

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
data = data.reshape(4, 3) ; data # 차원 변경 -> 2차원 4행 3열

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
data = np.arange(12).reshape(4, 3) ; data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
data > 5 # True, False 결과 출력

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
data[data > 5] = 7 # 5보다 큰 값 -> 7로 교체
data

array([[0, 1, 2],
       [3, 4, 5],
       [7, 7, 7],
       [7, 7, 7]])

In [57]:
data[ [data>5] ]

C:\Users\유수현\AppData\Local\Temp\ipykernel_11052\3096464695.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data[ [data>5] ]


array([7, 7, 7, 7, 7, 7])

In [58]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [7, 7, 7],
       [7, 7, 7]])

In [59]:
data = np.arange(1, 13, 1).reshape(4, 3) ; data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
data = np.arange(1, 24, 2).reshape(4, 3) ; data

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [61]:
data.sum()

144

In [62]:
data.mean()

12.0

In [60]:
data.mean(1) # 행단위로 평균 계산

array([ 3.,  9., 15., 21.])

In [86]:
data.mean(axis=1) # axis=1 행, axis=0 열

array([ 3.,  9., 15., 21.])

In [61]:
data.mean(0) # 열단위로 평균 계산

array([10., 12., 14.])

In [80]:
(data > 10).sum()

7

In [84]:
data[[data>10]].sum()

C:\Users\유수현\AppData\Local\Temp\ipykernel_11052\2922432276.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data[[data>10]].sum()


119

In [68]:
data[0]

array([1, 3, 5])

In [69]:
data[[0]]

array([[1, 3, 5]])

In [70]:
# 행의 순서를 임의의 순으로 바꿈
data[[1, 0]] # 1행, 0행 

array([[ 7,  9, 11],
       [ 1,  3,  5]])

In [71]:
data[1, 0] # 1행, 0열

7

In [85]:
# Transpose 전치
data.T

array([[ 1,  7, 13, 19],
       [ 3,  9, 15, 21],
       [ 5, 11, 17, 23]])

### random
- rand() : 0~1사이 균등분포의 random 수(실수)
- randint(start, end, count) : (start~(end-1)) 범위의 균등분포 count 개 random 수(정수))
- randn() : 정규(Gaussian) 분포의 random 수(평균 0, 표준편차 1), 0~1 사이 아님

In [97]:
import random as r # 내부 라이브러리

In [98]:
r.random() # 0~1 사이의 무작위 수를 추출

0.5832977773326298

In [99]:
for i in range(10):
    print(r.randint(1,7), end=' ') 
# randint(1,7): 1~7을 포함한 무작위 수

4 1 4 3 6 1 3 7 4 1 

In [102]:
for i in range(10):
    print(r.randrange(1,7), end=' ') 
# randrange(1, 7): 1~6을 7포함x 무작위 수

5 2 4 1 1 1 6 4 6 5 

In [103]:
z = np.random.randint(1, 100, 10) # 0~100 사이의 수 중 10개 추출
z

array([43, 34, 71, 60, 34, 76, 25, 15, 91, 78])

In [104]:
zz = np.random.rand(4) # 0~1 사이의 무작위 숫자 4개 추출
zz

array([0.03957745, 0.71958273, 0.37218913, 0.86084631])

In [105]:
zzz = np.random.randn(4) # 평균0, 표준편차 1인 주로 -1~1 근처의 값을 4개 추출 
zzz

array([ 0.33874883,  0.98718173, -0.62333067, -0.99490422])

In [107]:
z.sort()
z

array([15, 25, 34, 34, 43, 60, 71, 76, 78, 91])

In [108]:
np.sort(z) # 오름차순

array([15, 25, 34, 34, 43, 60, 71, 76, 78, 91])

In [109]:
np.sort(z)[::-1] # 내림차순

array([91, 78, 76, 71, 60, 43, 34, 34, 25, 15])

In [110]:
np.random.permutation(z) # z값을 랜덤으로 섞기

array([78, 15, 43, 34, 91, 34, 76, 71, 25, 60])

In [111]:
t = np.array([[8, 4, 11, 5], [2, 10, 7, 3], [9, 12, 1, 6]]) ; t

array([[ 8,  4, 11,  5],
       [ 2, 10,  7,  3],
       [ 9, 12,  1,  6]])

In [112]:
t.sort(1) ; t # 행단위로 정렬

array([[ 4,  5,  8, 11],
       [ 2,  3,  7, 10],
       [ 1,  6,  9, 12]])

In [113]:
t.sort(0) ; t # 열단위로 정렬

array([[ 1,  3,  7, 10],
       [ 2,  5,  8, 11],
       [ 4,  6,  9, 12]])

In [114]:
t.sort() ; t # 기본: 열단위로 정렬

array([[ 1,  3,  7, 10],
       [ 2,  5,  8, 11],
       [ 4,  6,  9, 12]])

In [117]:
print(np.linspace(0, 100, 5)) # 0~100사이 동일 간격으로 5개로 나누기
print(np.linspace(0, 1, 9))
print(np.linspace(0, 1)) # 기본: 50개로 나누기

[  0.  25.  50.  75. 100.]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [118]:
print(np.logspace(0, 5, 3))

[1.00000000e+00 3.16227766e+02 1.00000000e+05]


In [120]:
# 랜덤: 숫자들의 패턴 나열
np.random.seed(50) # 50번 랜덤을 사용하겠다 선언

for _ in range(3):
    print(np.random.rand(2), end='')

[0.49460165 0.2280831 ][0.25547392 0.39632991][0.3773151  0.99657423]